// Where props the crew made live: library/props/generated/<id>.js (an ES module importing ../core.js) plus
// meta.json (the record) and two mirrors the registry imports: meta.js (data for the compiler and browser) and
// index.js (static imports of the builders, since a browser cannot list a directory). Backend-only; no browse API.
import { existsSync, mkdirSync, readFileSync, renameSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { BASE_META } from "../../library/props/meta.js";
import { stripModule } from "./sandbox.ts";

export const GENERATED_DIR = join(dirname(fileURLToPath(import.meta.url)), "..", "..", "library", "props", "generated");

export interface GeneratedMeta {
  id: string;
  title: string;
  category: "generated";
  placement: string;
  source: { by: string; at: string; description: string };
  size: [number, number, number];
  y0: number;
  center: [number, number];
}
export type GeneratedMetaMap = Record<string, GeneratedMeta>;

const ID = /^[a-z0-9_]+$/;
const RESERVED = new Set(["index", "meta", "core", "default", "constructor", "prototype", "new", "class", "function", "return", "var", "let", "const", "if", "else", "for", "while", "do", "switch", "case", "break", "continue", "delete", "in", "of", "typeof", "void", "this", "null", "true", "false", "try", "catch", "throw", "with", "yield", "await", "async", "enum", "export", "import", "super", "static", "package", "interface", "private", "public", "protected", "implements", "instanceof", "debugger", "finally", "extends", "eval", "arguments", "box", "cyl", "mesh", "mat", "group", "merged", "finish", "rng", "TM", "THREE", "Math"]);
const FLAT = new Set(["onSurface", "wall", "ceiling", "flat"]);

/** An error message when the id cannot be used, else null. Built-in props are never replaceable; a generated id may be remade. */
export function idProblem(id: string): string | null {
  if (typeof id !== "string" || !ID.test(id)) return `prop id "${id}" must match [a-z0-9_]+ (lowercase letters, digits, underscores)`;
  if (/^\d/.test(id)) return `prop id "${id}" must not start with a digit (it is also the builder's function name)`;
  if (Object.prototype.hasOwnProperty.call(BASE_META, id)) return `prop id "${id}" already exists in the library; pick another id`;
  if (RESERVED.has(id)) return `prop id "${id}" is reserved`;
  return null;
}

export function loadGeneratedMeta(dir = GENERATED_DIR): GeneratedMetaMap {
  try { return JSON.parse(readFileSync(join(dir, "meta.json"), "utf8")) as GeneratedMetaMap; } catch { return {}; }
}

export function listGenerated(dir = GENERATED_DIR): string[] {
  return Object.keys(loadGeneratedMeta(dir)).filter((id) => existsSync(join(dir, `${id}.js`))).sort();
}

const write = (file: string, text: string) => { const tmp = `${file}.tmp`; writeFileSync(tmp, text); renameSync(tmp, file); };

/** The builder as an ES module: the model's code with its imports swapped for core.js, exporting the function. */
export function moduleSource(code: string, id: string, meta?: { by: string; at: string }): string {
  const body = stripModule(code).trim();
  return `// Made by the crew's prop maker${meta ? ` (${meta.by}, ${meta.at})` : ""}. Regenerated from the request; do not edit by hand.\nimport { THREE, box, cyl, mesh, mat, group, merged, mergeGeometries, TM, finish, rng } from "../core.js";\n\n${body}\n\nexport { ${id} };\n`;
}

/** The registry mirrors, rewritten from meta.json. */
function writeMirrors(dir: string, meta: GeneratedMetaMap) {
  const ids = Object.keys(meta).filter((id) => existsSync(join(dir, `${id}.js`))).sort();
  write(join(dir, "index.js"), `// Generated by the prop maker (src/assets/store.ts). Do not edit by hand.\n${ids.map((id) => `import { ${id} } from "./${id}.js";`).join("\n")}${ids.length ? "\n" : ""}export const GENERATED = { ${ids.join(", ")} };\n`);
  const full = Object.fromEntries(ids.map((id) => {
    const m = meta[id];
    return [id, { id, title: m.title, category: m.category, placement: m.placement, source: "new", module: "generated", size: m.size, y0: m.y0, center: m.center, ...(FLAT.has(m.placement) ? { decor: true } : {}) }];
  }));
  write(join(dir, "meta.js"), `// Generated by the prop maker (src/assets/store.ts). Do not edit by hand.\nexport const GENERATED_META = ${JSON.stringify(full, null, 2)};\n`);
}

export interface SaveInput {
  id: string;
  code: string;
  description: string;
  placement: string;
  /** measured by the checks, never written by the model */
  measured: { size: [number, number, number]; y0: number; center: [number, number] };
  by: string;
  at?: string;
  title?: string;
}

/** Save an accepted prop. Throws with a clear message when the id is taken or invalid. */
export function saveProp(s: SaveInput, dir = GENERATED_DIR): GeneratedMeta {
  const bad = idProblem(s.id);
  if (bad) throw new Error(bad);
  mkdirSync(dir, { recursive: true });
  const r2 = (x: number) => Math.round(x * 100) / 100;
  const at = s.at ?? new Date().toISOString();
  const meta: GeneratedMeta = {
    id: s.id, title: s.title ?? s.id.replace(/_/g, " "), category: "generated", placement: s.placement,
    source: { by: s.by, at, description: s.description },
    size: s.measured.size.map(r2) as [number, number, number], y0: r2(s.measured.y0), center: s.measured.center.map(r2) as [number, number],
  };
  write(join(dir, `${s.id}.js`), moduleSource(s.code, s.id, { by: s.by, at }));
  const all = { ...loadGeneratedMeta(dir), [s.id]: meta };
  write(join(dir, "meta.json"), JSON.stringify(all, null, 2) + "\n");
  writeMirrors(dir, all);
  return meta;
}

/** Remove a generated prop (a rejected take discards it). Returns false when there was none. */
export function removeProp(id: string, dir = GENERATED_DIR): boolean {
  const all = loadGeneratedMeta(dir);
  if (!all[id]) return false;
  delete all[id];
  rmSync(join(dir, `${id}.js`), { force: true });
  write(join(dir, "meta.json"), JSON.stringify(all, null, 2) + "\n");
  writeMirrors(dir, all);
  return true;
}
